travis:
  secure:
    BINSTAR_TOKEN: CkQNN1G1JveggiZ1m3hQBxYinkmVgPXKxCwgjN9gfKYu7bHFCQIcQIyFHRORO6WZw37xFcIKrtS/13xIXt6Gt0rQWhcwHljFznZOOe66tzS7aHGXnSh6lp8e0HmGT+eFvSRQY16wuS/nA7AjKqJqzquwgJDccwhsqebd6LLmgH47ARtD2oKYLBJ//CO8t5ydcs2kU8xO/v2k4IQ/xKCQvHNvCk1YhJpvUsOdbqp0+3L6revClENTULlvVG6EJBz/hdfpIaX6FfIFr0xHk9QGOkBKJcAmE9CjuLdpUriyJkuiQtQHf6Fa6iamP5ndDFgtiVbBtPRM9P3CKfeSUK6eNjEFY7EDG313c5fouGi55Jmy6uiU+1HvR7tKpZy6EXRQ4nhWBKuTPHFTHBNt/BvTk2bRTXIx/F+cado1OWoJww+gz///yvbNFSOSUXbycPLvYhkrjV8cxo+Z6yYam4itADAv0CGHLfEBUqDwpyysYFRDbbTJatkT6ELbrHeb6IhtcH5UtwxUQnNWr1LNRurNDXzVjXzUKi6N6saBQJgYaWA8m92QRkQAyx/HzwdaTqpS8WS7uSY9dBIO6kBl3HUBXz0gpfrXwNAil/YogWkkfnv1srkHPnsoMTvHTkFqsgRKqOioiKHqlfYZ/XbUIhQXYlcIP0gEU9IIQm5/9cuzyFs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
